### ISSUE TITLE
potentially missing part

### ISSUE THREAD

**Issue by hosseinjavidnia** [ubisoft/ubisoft-laforge-FFHQ-UV-Intrinsics#1]
Hi,
Thanks for sharing your dataset. It seems like `ffhq-uv-intrinsics-2.zip` is missing form the repo. 
Can you please confirm if the current structure is correct?

Many thanks

**Comment by abdallahdib** [comment]
Hi and thanks for reporting the missing zip file. Can you plz check that after you downloaded and unzipped  all the  files, you are getting a folder that contains 10K sub-folders ? 
Thanks

**Comment by hosseinjavidnia** [comment]
Thank you for responding.
After unzipping all the files, I have 9630 sub-folders. To be specific the sub-folders between `000739` and `001110` are missing.

Many thanks

**Comment by abdallahdib** [comment]
Thanks for reporting the missing folders, we will fix this 

Best 

AD

**Comment by luizgh** [comment]
@hosseinjavidnia  - we added the missing file, can you please check?

**Comment by hosseinjavidnia** [comment]
Thanks for the fix. 
There is now 10K sub-folders.

**Comment by luizgh** [comment]
Ok. Thanks for the bug report @hosseinjavidnia !
